package ui;

import dao.ActivityLogDAO;
import dao.StudentDAO;
import model.Student;
import model.User;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;

/**
 * StudentPanel - Complete Student CRUD Management.
 */
public class StudentPanel extends JPanel {

    private final StudentDAO studentDAO;
    private final ActivityLogDAO logDAO;
    private final User currentUser;

    // Form Components
    private JTextField txtStudentId;
    private JTextField txtRollNo;
    private JTextField txtName;
    private JComboBox<String> cmbGender;
    private JTextField txtPhone;
    private JTextField txtEmail;
    private JComboBox<String> cmbCourse;
    private JComboBox<String> cmbYear;
    private JTextArea txtAddress;

    // Buttons
    private JButton btnAdd;
    private JButton btnUpdate;
    private JButton btnDelete;
    private JButton btnClear;

    // Search and Table
    private JTextField txtSearch;
    private JButton btnSearch;
    private JButton btnResetSearch;
    private JTable studentTable;
    private DefaultTableModel tableModel;

    public StudentPanel(User currentUser) {
        this.currentUser = currentUser;
        this.studentDAO = new StudentDAO();
        this.logDAO = new ActivityLogDAO();
        initComponents();
        loadStudentData();
    }

    public StudentPanel() {
        this(null);
    }

    private void initComponents() {
        setLayout(new BorderLayout(15, 15));
        setBackground(UIUtils.COLOR_BG);
        setBorder(new EmptyBorder(15, 20, 15, 20));

        // Top Title
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setOpaque(false);
        headerPanel.add(UIUtils.createHeaderLabel("Student Management"), BorderLayout.WEST);
        add(headerPanel, BorderLayout.NORTH);

        // Center Split: Left = Form, Right = Table + Search
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        splitPane.setDividerLocation(380);
        splitPane.setContinuousLayout(true);
        splitPane.setOpaque(false);
        splitPane.setBorder(null);

        // Left Form Panel
        JPanel formCard = UIUtils.createCardPanel();
        formCard.setLayout(new BorderLayout(0, 10));

        JLabel lblFormTitle = new JLabel("Student Information Form");
        lblFormTitle.setFont(UIUtils.FONT_SUBTITLE);
        lblFormTitle.setForeground(UIUtils.COLOR_PRIMARY);
        formCard.add(lblFormTitle, BorderLayout.NORTH);

        JPanel fieldsPanel = new JPanel(new GridBagLayout());
        fieldsPanel.setOpaque(false);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(4, 5, 4, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        int row = 0;

        // Student ID (Auto/Readonly)
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.35;
        fieldsPanel.add(UIUtils.createFormLabel("Student ID:"), gbc);
        gbc.gridx = 1; gbc.gridy = row++; gbc.weightx = 0.65;
        txtStudentId = new JTextField();
        txtStudentId.setEditable(false);
        txtStudentId.setBackground(new Color(241, 245, 249));
        txtStudentId.setToolTipText("Auto-generated by system");
        fieldsPanel.add(txtStudentId, gbc);

        // Roll Number
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Roll Number * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        txtRollNo = new JTextField();
        fieldsPanel.add(txtRollNo, gbc);

        // Name
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Full Name * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        txtName = new JTextField();
        fieldsPanel.add(txtName, gbc);

        // Gender
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Gender * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        cmbGender = new JComboBox<>(new String[]{"Male", "Female", "Other"});
        fieldsPanel.add(cmbGender, gbc);

        // Phone
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Phone (10 Digits) * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        txtPhone = new JTextField();
        fieldsPanel.add(txtPhone, gbc);

        // Email
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Email Address * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        txtEmail = new JTextField();
        fieldsPanel.add(txtEmail, gbc);

        // Course
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Course * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        cmbCourse = new JComboBox<>(new String[]{
            "Diploma in Computer Engg",
            "Diploma in Information Tech",
            "Diploma in Mechanical Engg",
            "Diploma in Electrical Engg",
            "Diploma in Civil Engg",
            "Diploma in Electronics"
        });
        cmbCourse.setEditable(true);
        fieldsPanel.add(cmbCourse, gbc);

        // Year
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Academic Year * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        cmbYear = new JComboBox<>(new String[]{"1st Year", "2nd Year", "3rd Year"});
        fieldsPanel.add(cmbYear, gbc);

        // Address
        gbc.gridx = 0; gbc.gridy = row;
        fieldsPanel.add(UIUtils.createFormLabel("Address * :"), gbc);
        gbc.gridx = 1; gbc.gridy = row++;
        txtAddress = new JTextArea(3, 15);
        txtAddress.setLineWrap(true);
        txtAddress.setWrapStyleWord(true);
        txtAddress.setFont(UIUtils.FONT_REGULAR);
        JScrollPane scrollAddress = new JScrollPane(txtAddress);
        fieldsPanel.add(scrollAddress, gbc);

        formCard.add(new JScrollPane(fieldsPanel), BorderLayout.CENTER);

        // Form Buttons
        JPanel actionBtnPanel = new JPanel(new GridLayout(2, 2, 8, 8));
        actionBtnPanel.setOpaque(false);
        actionBtnPanel.setBorder(new EmptyBorder(8, 0, 0, 0));

        btnAdd = UIUtils.createPrimaryButton("Add Student");
        btnUpdate = UIUtils.createSuccessButton("Update");
        btnDelete = UIUtils.createDangerButton("Delete");
        btnClear = UIUtils.createSecondaryButton("Clear Form");

        actionBtnPanel.add(btnAdd);
        actionBtnPanel.add(btnUpdate);
        actionBtnPanel.add(btnDelete);
        actionBtnPanel.add(btnClear);

        formCard.add(actionBtnPanel, BorderLayout.SOUTH);
        splitPane.setLeftComponent(formCard);

        // Right Table & Search Panel
        JPanel rightPanel = UIUtils.createCardPanel();
        rightPanel.setLayout(new BorderLayout(0, 10));

        // Search Bar Panel
        JPanel searchBar = new JPanel(new BorderLayout(8, 0));
        searchBar.setOpaque(false);
        searchBar.setBorder(new EmptyBorder(0, 0, 8, 0));

        JLabel lblSearch = new JLabel("Search Students: ");
        lblSearch.setFont(UIUtils.FONT_BOLD);
        searchBar.add(lblSearch, BorderLayout.WEST);

        txtSearch = new JTextField();
        txtSearch.setFont(UIUtils.FONT_REGULAR);
        searchBar.add(txtSearch, BorderLayout.CENTER);

        JPanel searchBtns = new JPanel(new FlowLayout(FlowLayout.RIGHT, 5, 0));
        searchBtns.setOpaque(false);
        btnSearch = UIUtils.createPrimaryButton("Search");
        btnResetSearch = UIUtils.createSecondaryButton("Reset");
        searchBtns.add(btnSearch);
        searchBtns.add(btnResetSearch);
        searchBar.add(searchBtns, BorderLayout.EAST);

        rightPanel.add(searchBar, BorderLayout.NORTH);

        // Table
        String[] columns = {"ID", "Roll No", "Full Name", "Gender", "Phone", "Email", "Course", "Year", "Address"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };

        studentTable = new JTable(tableModel);
        UIUtils.styleTable(studentTable);
        studentTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Table Selection listener: populate form fields
        studentTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && studentTable.getSelectedRow() != -1) {
                int r = studentTable.getSelectedRow();
                txtStudentId.setText(tableModel.getValueAt(r, 0).toString());
                txtRollNo.setText(tableModel.getValueAt(r, 1).toString());
                txtName.setText(tableModel.getValueAt(r, 2).toString());
                cmbGender.setSelectedItem(tableModel.getValueAt(r, 3).toString());
                txtPhone.setText(tableModel.getValueAt(r, 4).toString());
                txtEmail.setText(tableModel.getValueAt(r, 5).toString());
                cmbCourse.setSelectedItem(tableModel.getValueAt(r, 6).toString());
                cmbYear.setSelectedItem(tableModel.getValueAt(r, 7).toString());
                txtAddress.setText(tableModel.getValueAt(r, 8).toString());
            }
        });

        rightPanel.add(new JScrollPane(studentTable), BorderLayout.CENTER);
        splitPane.setRightComponent(rightPanel);

        add(splitPane, BorderLayout.CENTER);

        // Register Action Listeners
        btnAdd.addActionListener(e -> handleAddStudent());
        btnUpdate.addActionListener(e -> handleUpdateStudent());
        btnDelete.addActionListener(e -> handleDeleteStudent());
        btnClear.addActionListener(e -> clearForm());
        btnSearch.addActionListener(e -> handleSearch());
        btnResetSearch.addActionListener(e -> {
            txtSearch.setText("");
            loadStudentData();
        });
        txtSearch.addActionListener(e -> handleSearch());
    }

    /**
     * Loads all students from MySQL into the JTable.
     */
    public void loadStudentData() {
        tableModel.setRowCount(0);
        List<Student> students = studentDAO.getAllStudents();
        for (Student s : students) {
            tableModel.addRow(new Object[]{
                s.getStudentId(),
                s.getRollNo(),
                s.getName(),
                s.getGender(),
                s.getPhone(),
                s.getEmail(),
                s.getCourse(),
                s.getYear(),
                s.getAddress()
            });
        }
    }

    private void handleAddStudent() {
        if (!validateForm(0)) return;

        Student s = new Student(
            txtRollNo.getText().trim(),
            txtName.getText().trim(),
            cmbGender.getSelectedItem().toString(),
            txtPhone.getText().trim(),
            txtEmail.getText().trim(),
            cmbCourse.getSelectedItem().toString(),
            cmbYear.getSelectedItem().toString(),
            txtAddress.getText().trim()
        );

        try {
            if (studentDAO.addStudent(s)) {
                logDAO.log(currentUser, "STUDENT_ADD", 
                    "Registered student " + s.getName() + " (Roll No: " + s.getRollNo() + ", Course: " + s.getCourse() + ").");
                JOptionPane.showMessageDialog(this, 
                    "Student registered successfully with ID: " + s.getStudentId(), 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                loadStudentData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to register student.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleUpdateStudent() {
        if (txtStudentId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a student from the table to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int studentId = Integer.parseInt(txtStudentId.getText().trim());
        if (!validateForm(studentId)) return;

        Student s = new Student(
            studentId,
            txtRollNo.getText().trim(),
            txtName.getText().trim(),
            cmbGender.getSelectedItem().toString(),
            txtPhone.getText().trim(),
            txtEmail.getText().trim(),
            cmbCourse.getSelectedItem().toString(),
            cmbYear.getSelectedItem().toString(),
            txtAddress.getText().trim()
        );

        try {
            if (studentDAO.updateStudent(s)) {
                logDAO.log(currentUser, "STUDENT_UPDATE", 
                    "Updated student details for " + s.getName() + " (Roll No: " + s.getRollNo() + ").");
                JOptionPane.showMessageDialog(this, "Student updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadStudentData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Update failed. Student record not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleDeleteStudent() {
        if (txtStudentId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a student from the table to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int studentId = Integer.parseInt(txtStudentId.getText().trim());
        String studentName = txtName.getText().trim();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete student: " + studentName + " (ID: " + studentId + ")?\n" +
            "Note: If this student has active room allocations, the system will prevent deletion.",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (studentDAO.deleteStudent(studentId)) {
                    logDAO.log(currentUser, "STUDENT_DELETE", 
                        "Deleted student record: " + studentName + " (ID: " + studentId + ").");
                    JOptionPane.showMessageDialog(this, "Student deleted successfully.", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                    loadStudentData();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Student could not be deleted.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Cannot delete student: This student is currently allocated to a room or has related records.\nDetails: " + ex.getMessage(), 
                    "Constraint Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void handleSearch() {
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadStudentData();
            return;
        }

        tableModel.setRowCount(0);
        List<Student> results = studentDAO.searchStudents(keyword);
        for (Student s : results) {
            tableModel.addRow(new Object[]{
                s.getStudentId(),
                s.getRollNo(),
                s.getName(),
                s.getGender(),
                s.getPhone(),
                s.getEmail(),
                s.getCourse(),
                s.getYear(),
                s.getAddress()
            });
        }
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No students found matching: " + keyword, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean validateForm(int excludeId) {
        String roll = txtRollNo.getText().trim();
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();

        if (roll.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Roll Number is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtRollNo.requestFocus();
            return false;
        }

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student Name is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return false;
        }

        // Check roll number uniqueness
        if (studentDAO.isRollNoExists(roll, excludeId)) {
            JOptionPane.showMessageDialog(this, "Roll Number '" + roll + "' is already assigned to another student.", "Duplicate Roll Number", JOptionPane.ERROR_MESSAGE);
            txtRollNo.requestFocus();
            return false;
        }

        // Phone validation (10 digits)
        if (!phone.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Phone Number must be exactly 10 digits.", "Invalid Phone", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
            return false;
        }

        // Basic Email validation
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address (e.g. student@example.com).", "Invalid Email", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return false;
        }

        if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtAddress.requestFocus();
            return false;
        }

        return true;
    }

    private void clearForm() {
        txtStudentId.setText("");
        txtRollNo.setText("");
        txtName.setText("");
        cmbGender.setSelectedIndex(0);
        txtPhone.setText("");
        txtEmail.setText("");
        cmbCourse.setSelectedIndex(0);
        cmbYear.setSelectedIndex(0);
        txtAddress.setText("");
        studentTable.clearSelection();
    }
}
